Move exit_type destroy restriction from controller to model
rubyforgood/abalone pull request #935
Opened 2021-12-22 17:16 UTC by mattwd7

Follow-through related to #901 

### Description
This commit moves the ExitType destroy restriction from the exit_types_controller to the model.

### Type of change
Refactor

### How Has This Been Tested?

Additional spec examples added to ExitType model

2021-12-23 18:28 UTC, CraigJZ requested changes
@mattwd7 Thanks for this refactor! I think we just need one small change in the Exit Type specs.

2021-12-23 18:28 UTC, CraigJZ commented on spec/models/exit_type_spec.rb
> +          .not_to change(MeasurementType, :count)
Just one minor change. I think this spec should check that the ExitType count has not changed.

2021-12-24 01:15 UTC, mattwd7 commented
Oh oops! I'll update

2022-01-03 23:11 UTC, CraigJZ approved these changes
Thanks for making that update. Looks great!!

2022-01-03 23:11 UTC, merged